-- v1.3.2 HookBus runtime execution records.
CREATE TABLE IF NOT EXISTS hook_executions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  hook_name VARCHAR(128) NOT NULL,
  plugin_code VARCHAR(64) NOT NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'non_blocking',
  content_type VARCHAR(64) NOT NULL DEFAULT '',
  content_id BIGINT UNSIGNED NULL,
  community_id BIGINT UNSIGNED NULL,
  category_id BIGINT UNSIGNED NULL,
  actor_type VARCHAR(32) NOT NULL DEFAULT '',
  actor_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  admin_user_id BIGINT UNSIGNED NULL,
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  duration_ms INT NOT NULL DEFAULT 0,
  success TINYINT(1) NOT NULL DEFAULT 1,
  error_message TEXT NULL,
  blocking TINYINT(1) NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hook_executions_plugin_hook (plugin_code, hook_name),
  KEY idx_hook_executions_success (plugin_code, success, started_at),
  KEY idx_hook_executions_content (content_id),
  KEY idx_hook_executions_community (community_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
