import { http } from './http';

export const login = (payload) => http.post('/admin/login', payload);
export const logout = (refreshToken) => http.post('/admin/logout', { refresh_token: refreshToken });
export const me = () => http.get('/admin/me');
export const sites = () => http.get('/sites');
export const boards = () => http.get('/boards');
export const plugins = () => http.get('/admin/plugins');
export const pluginMenus = () => http.get('/admin/plugin-menus');
export const enablePlugin = (code) => http.post(`/admin/plugins/${code}/enable`);
export const disablePlugin = (code) => http.post(`/admin/plugins/${code}/disable`);
export const adminCommunities = (params) => http.get('/admin/communities', { params });
export const createCommunity = (payload) => http.post('/admin/communities', payload);
export const adminCommunity = (id) => http.get(`/admin/communities/${id}`);
export const updateCommunity = (id, payload) => http.put(`/admin/communities/${id}`, payload);
export const enableCommunity = (id) => http.post(`/admin/communities/${id}/enable`);
export const disableCommunity = (id) => http.post(`/admin/communities/${id}/disable`);
export const reorderCommunities = (payload) => http.post('/admin/communities/reorder', payload);
export const adminCommunityPlugins = (id) => http.get(`/admin/communities/${id}/plugins`);
export const enableCommunityPlugin = (id, code) => http.post(`/admin/communities/${id}/plugins/${code}/enable`);
export const disableCommunityPlugin = (id, code) => http.post(`/admin/communities/${id}/plugins/${code}/disable`);
export const updateCommunityPluginConfig = (id, code, payload) => http.put(`/admin/communities/${id}/plugins/${code}/config`, payload);
export const reorderCommunityPlugins = (id, payload) => http.put(`/admin/communities/${id}/plugins/sort`, payload);
export const adminCommunityCategories = (id) => http.get(`/admin/communities/${id}/categories`);
export const createCommunityCategory = (id, payload) => http.post(`/admin/communities/${id}/categories`, payload);
export const updateCategory = (id, payload) => http.put(`/admin/categories/${id}`, payload);
export const enableCategory = (id) => http.post(`/admin/categories/${id}/enable`);
export const disableCategory = (id) => http.post(`/admin/categories/${id}/disable`);
export const reorderCategories = (payload) => http.post('/admin/categories/reorder', payload);
export const overview = (site) => http.get('/admin/overview', { params: { site } });
export const posts = (params) => http.get('/admin/posts', { params });
export const createPost = (payload) => http.post('/admin/posts', payload);
export const updatePost = (id, payload) => http.put(`/admin/posts/${id}`, payload);
export const deletePost = (id) => http.delete(`/admin/posts/${id}`);
export const batchTopics = (payload) => http.post('/admin/topics/batch', payload);
export const featureTopic = (id) => http.post(`/admin/topics/${id}/feature`);
export const pinTopic = (id) => http.post(`/admin/topics/${id}/pin`);
export const hideTopic = (id) => http.post(`/admin/topics/${id}/hide`);
export const restoreTopic = (id) => http.post(`/admin/topics/${id}/restore`);
export const lockTopicComments = (id) => http.post(`/admin/topics/${id}/lock-comments`);
export const unlockTopicComments = (id) => http.post(`/admin/topics/${id}/unlock-comments`);
export const comments = (site) => http.get('/admin/comments', { params: { site } });
export const updateComment = (id, payload) => http.put(`/admin/comments/${id}/status`, payload);
export const hideComment = (id) => http.post(`/admin/comments/${id}/hide`);
export const restoreComment = (id) => http.post(`/admin/comments/${id}/restore`);
export const deleteComment = (id) => http.delete(`/admin/comments/${id}`);
export const batchComments = (payload) => http.post('/admin/comments/batch', payload);
export const reports = (params) => http.get('/admin/reports', { params });
export const report = (id) => http.get(`/admin/reports/${id}`);
export const handleReport = (id, payload) => http.post(`/admin/reports/${id}/handle`, payload);
export const batchReports = (payload) => http.post('/admin/reports/batch-handle', payload);
export const batchHandleReports = batchReports;
export const moderators = (params) => http.get('/admin/moderators', { params });
export const createModerator = (payload) => http.post('/admin/moderators', payload);
export const updateModerator = (id, payload) => http.put(`/admin/moderators/${id}`, payload);
export const deleteModerator = (id) => http.delete(`/admin/moderators/${id}`);
export const updateModeratorStatus = (id, status) => http.put(`/admin/moderators/${id}`, { status });
export const users = () => http.get('/admin/users');
export const updateUserStatus = (id, payload) => http.put(`/admin/users/${id}/status`, payload);
export const roles = () => http.get('/admin/roles');
export const permissions = () => http.get('/admin/permissions');
export const tags = (params) => http.get('/admin/tags', { params });
export const tag = (id) => http.get(`/admin/tags/${id}`);
export const tagTopics = (id, params) => http.get(`/admin/tags/${id}/topics`, { params });
export const tagAliases = (id) => http.get(`/admin/tags/${id}/aliases`);
export const createTag = (payload) => http.post('/admin/tags', payload);
export const updateTag = (id, payload) => http.put(`/admin/tags/${id}`, payload);
export const createTagAlias = (id, payload) => http.post(`/admin/tags/${id}/aliases`, payload);
export const deleteTagAlias = (id, aliasId) => http.delete(`/admin/tags/${id}/aliases/${aliasId}`);
export const enableTag = (id) => http.post(`/admin/tags/${id}/enable`);
export const disableTag = (id) => http.post(`/admin/tags/${id}/disable`);
export const mergeTag = (id, payload) => http.post(`/admin/tags/${id}/merge`, payload);
export const recalculateTag = (id) => http.post(`/admin/tags/${id}/recalculate`);
export const recalculateAllTags = () => http.post('/admin/tags/recalculate-all');
export const logs = (site) => http.get('/admin/logs', { params: { site } });
export const auditLogs = (params) => http.get('/admin/audit-logs', { params });
export const settings = () => http.get('/admin/settings');
export const updateSettings = (payload) => http.put('/admin/settings', payload);
export const notices = (site) => http.get('/notifications', { params: { site } });
export const pushNotice = (payload) => http.post('/admin/notifications', payload);
