import { http } from './http';

export const login = (payload) => http.post('/admin/login', payload);
export const logout = (refreshToken) => http.post('/admin/logout', { refresh_token: refreshToken });
export const me = () => http.get('/admin/me');
export const sites = () => http.get('/sites');
export const boards = () => http.get('/boards');
export const plugins = () => http.get('/admin/plugins');
export const pluginHealthSummary = () => http.get('/admin/plugins/health');
export const pluginMenus = () => http.get('/admin/plugin-menus');
export const pluginHealth = (code) => http.get(`/admin/plugins/${code}/health`);
export const pluginReadiness = (code, params) => http.get(`/admin/plugins/${code}/readiness`, { params });
export const pluginMenusPreview = (code, params) => http.get(`/admin/plugins/${code}/menus/preview`, { params });
export const validatePluginManifest = (payload) => http.post('/admin/plugins/manifest/validate', payload);
export const dryRunPluginManifest = (payload) => http.post('/admin/plugins/dry-run', payload);
export const dryRunPluginUpgrade = (code, payload) => http.post(`/admin/plugins/${code}/upgrade/dry-run`, payload);
export const upgradePlugin = (code, payload) => http.post(`/admin/plugins/${code}/upgrade`, payload);
// v1.7.0-P0-08: compat-check driven package upgrade (no auto-enable, no migrations executed)
export const pluginUpgradeImpact = (code, params) => http.get(`/admin/plugins/${encodeURIComponent(code)}/upgrade-impact`, { params });
export const upgradePluginFromPackage = (code, payload) => http.post(`/admin/plugins/${encodeURIComponent(code)}/upgrade-from-package`, payload);
export const listPluginUpgradeTasks = (params) => http.get('/admin/plugins/upgrade-tasks', { params });
export const getPluginUpgradeTask = (id) => http.get(`/admin/plugins/upgrade-tasks/${id}`);
export const retryPluginUpgradeTask = (id) => http.post(`/admin/plugins/upgrade-tasks/${id}/retry`);
export const deletePluginUpgradeTask = (id) => http.delete(`/admin/plugins/upgrade-tasks/${id}`);
export const dryRunPluginExport = (code, payload) => http.post(`/admin/plugins/${code}/export/dry-run`, payload);
export const exportPluginPackage = (code, payload) => http.post(`/admin/plugins/${code}/export`, payload);
export const installPluginManifest = (payload) => http.post('/admin/plugins/install', payload);
export const previewPluginPackageTemplate = (payload) => http.post('/admin/plugins/packages/templates/preview', payload);
export const createPluginPackageTemplate = (payload) => http.post('/admin/plugins/packages/templates', payload);
export const dryRunPluginPackage = (payload) => http.post('/admin/plugins/packages/dry-run', payload);
export const uploadPluginPackageZip = (formData) => http.post('/admin/plugins/packages/upload', formData, { headers: { 'Content-Type': 'multipart/form-data' } });
export const listPluginPackageUploads = (params) => http.get('/admin/plugins/packages/uploads', { params });
export const getPluginPackageUpload = (uploadId) => http.get(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}`);
export const rescanPluginPackageUpload = (uploadId) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/rescan`);
export const cancelPluginPackageUpload = (uploadId) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/cancel`);
export const deletePluginPackageUpload = (uploadId) => http.delete(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}`);
export const cleanupPluginPackageUploads = () => http.post('/admin/plugins/packages/uploads/cleanup');
export const submitPluginPackageUploadApproval = (uploadId, payload = {}) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/approval`, payload);
export const approvePluginPackageUpload = (uploadId, payload = {}) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/approve`, payload);
export const rejectPluginPackageUpload = (uploadId, payload = {}) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/reject`, payload);
export const promotePluginPackageUpload = (uploadId, payload = {}) => http.post(`/admin/plugins/packages/uploads/${encodeURIComponent(uploadId)}/promote`, payload);
export const downloadPluginPackageToStaging = (payload) => http.post('/admin/plugins/packages/download', payload);
export const listPluginPackageStaging = (params) => http.get('/admin/plugins/packages/staging', { params });
export const getPluginPackageStaging = (id) => http.get(`/admin/plugins/packages/staging/${id}`);
export const deletePluginPackageStaging = (id) => http.delete(`/admin/plugins/packages/staging/${id}`);
export const runPluginPackageCompatCheck = (precheckId) => http.post(`/admin/plugins/packages/prechecks/${precheckId}/compat-check`);
export const listPluginPackageCompatChecks = (params) => http.get('/admin/plugins/packages/compat-checks', { params });
export const getPluginPackageCompatCheck = (id) => http.get(`/admin/plugins/packages/compat-checks/${id}`);
export const deletePluginPackageCompatCheck = (id) => http.delete(`/admin/plugins/packages/compat-checks/${id}`);
export const verifyPluginPackageSignature = (precheckId) => http.post(`/admin/plugins/packages/prechecks/${precheckId}/verify-signature`);
export const listPluginPackageSignatures = (params) => http.get('/admin/plugins/packages/signatures', { params });
export const getPluginPackageSignature = (id) => http.get(`/admin/plugins/packages/signatures/${id}`);
export const deletePluginPackageSignature = (id) => http.delete(`/admin/plugins/packages/signatures/${id}`);
export const runPluginEnablePrecheck = (code) => http.post(`/admin/plugins/${encodeURIComponent(code)}/enable-precheck`);
export const listPluginEnablePrechecks = (params) => http.get('/admin/plugins/enable-prechecks', { params });
export const getPluginEnablePrecheck = (id) => http.get(`/admin/plugins/enable-prechecks/${id}`);
export const deletePluginEnablePrecheck = (id) => http.delete(`/admin/plugins/enable-prechecks/${id}`);
export const enablePluginFromEnablePrecheck = (id) => http.post(`/admin/plugins/enable-prechecks/${id}/enable`);
export const listPluginEnableTasks = (params) => http.get('/admin/plugins/enable-tasks', { params });
export const getPluginEnableTask = (id) => http.get(`/admin/plugins/enable-tasks/${id}`);
export const retryPluginEnableTask = (id) => http.post(`/admin/plugins/enable-tasks/${id}/retry`);
export const deletePluginEnableTask = (id) => http.delete(`/admin/plugins/enable-tasks/${id}`);
export const getPluginConfigKeyStatus = () => http.get('/admin/plugins/config-keys/status');
export const dryRunPluginConfigKeyRotation = (payload) => http.post('/admin/plugins/config-keys/rotation/dry-run', payload);
export const reencryptPluginConfigKeys = (payload) => http.post('/admin/plugins/config-keys/rotation/re-encrypt', payload);
export const listPluginRemoteIndexes = (params) => http.get('/admin/plugins/remote-indexes', { params });
export const createPluginRemoteIndex = (payload) => http.post('/admin/plugins/remote-indexes', payload);
export const updatePluginRemoteIndex = (id, payload) => http.put(`/admin/plugins/remote-indexes/${id}`, payload);
export const enablePluginRemoteIndex = (id) => http.post(`/admin/plugins/remote-indexes/${id}/enable`);
export const disablePluginRemoteIndex = (id) => http.post(`/admin/plugins/remote-indexes/${id}/disable`);
export const deletePluginRemoteIndex = (id) => http.delete(`/admin/plugins/remote-indexes/${id}`);
export const fetchPluginRemoteIndex = (id) => http.post(`/admin/plugins/remote-indexes/${id}/fetch`);
export const listPluginRemoteIndexPlugins = (id, params) => http.get(`/admin/plugins/remote-indexes/${id}/plugins`, { params });
export const getPluginRemoteIndexPlugin = (id, code) => http.get(`/admin/plugins/remote-indexes/${id}/plugins/${encodeURIComponent(code)}`);
export const listPluginVersions = (params) => http.get('/admin/plugins/versions', { params });
export const listPluginCodeVersions = (code) => http.get(`/admin/plugins/${encodeURIComponent(code)}/versions`);
export const getPluginVersionDetail = (code, version, params) => http.get(`/admin/plugins/${encodeURIComponent(code)}/versions/${encodeURIComponent(version)}`, { params });
export const dryRunPluginVersionUpgradeDiff = (code, version, payload) => http.post(`/admin/plugins/${encodeURIComponent(code)}/versions/${encodeURIComponent(version)}/upgrade-diff`, payload);
export const listPluginOperations = (params) => http.get('/admin/plugins/operations', { params });
export const getPluginOperation = (operationId) => http.get(`/admin/plugins/operations/${encodeURIComponent(operationId)}`);
export const recoverPluginOperationDryRun = (operationId) => http.post(`/admin/plugins/operations/${encodeURIComponent(operationId)}/recover/dry-run`);
export const cleanupPluginOperation = (operationId) => http.post(`/admin/plugins/operations/${encodeURIComponent(operationId)}/cleanup`);
export const dryRunPluginUpgradeRollback = (code, payload) => http.post(`/admin/plugins/${encodeURIComponent(code)}/rollback/dry-run`, payload);
export const listTrustedPublishers = (params) => http.get('/admin/plugins/trusted-publishers', { params });
export const getTrustedPublisher = (id) => http.get(`/admin/plugins/trusted-publishers/${id}`);
export const createTrustedPublisher = (payload) => http.post('/admin/plugins/trusted-publishers', payload);
export const updateTrustedPublisher = (id, payload) => http.put(`/admin/plugins/trusted-publishers/${id}`, payload);
export const blockTrustedPublisher = (id, payload = {}) => http.post(`/admin/plugins/trusted-publishers/${id}/block`, payload);
export const revokeTrustedPublisher = (id, payload = {}) => http.post(`/admin/plugins/trusted-publishers/${id}/revoke`, payload);
export const restoreTrustedPublisher = (id, payload = {}) => http.post(`/admin/plugins/trusted-publishers/${id}/restore`, payload);
export const deleteTrustedPublisher = (id) => http.delete(`/admin/plugins/trusted-publishers/${id}`);
export const listPluginPackages = (params) => http.get('/admin/plugins/packages', { params });
export const getPluginPackageDetail = (params) => http.get('/admin/plugins/packages/detail', { params });
export const installPluginPackage = (payload) => http.post('/admin/plugins/packages/install', payload);
// plugin approvals (v1.5.0-P1-07)
export const createPluginApproval = (payload) => http.post('/admin/plugins/approvals', payload);
export const listPluginApprovals = (params) => http.get('/admin/plugins/approvals', { params });
export const getPluginApproval = (id) => http.get(`/admin/plugins/approvals/${id}`);
export const approvePluginApproval = (id, payload) => http.post(`/admin/plugins/approvals/${id}/approve`, payload);
export const rejectPluginApproval = (id, payload) => http.post(`/admin/plugins/approvals/${id}/reject`, payload);
export const cancelPluginApproval = (id, payload) => http.post(`/admin/plugins/approvals/${id}/cancel`, payload);
export const executePluginApproval = (id) => http.post(`/admin/plugins/approvals/${id}/execute`);
export const listPluginConfigVersions = (code, params) => http.get(`/admin/plugins/${code}/config/versions`, { params });
export const getPluginConfigVersionDetail = (code, versionId) => http.get(`/admin/plugins/${code}/config/versions/${versionId}`);
export const dryRunPluginConfigRollback = (code, versionId) => http.post(`/admin/plugins/${code}/config/versions/${versionId}/rollback/dry-run`);
export const listCommunityPluginConfigVersions = (communityId, code, params) => http.get(`/admin/communities/${communityId}/plugins/${code}/config/versions`, { params });
export const getCommunityPluginConfigVersionDetail = (communityId, code, versionId) => http.get(`/admin/communities/${communityId}/plugins/${code}/config/versions/${versionId}`);
export const dryRunCommunityPluginConfigRollback = (communityId, code, versionId) => http.post(`/admin/communities/${communityId}/plugins/${code}/config/versions/${versionId}/rollback/dry-run`);
export const enablePlugin = (code) => http.post(`/admin/plugins/${code}/enable`);
export const disablePlugin = (code) => http.post(`/admin/plugins/${code}/disable`);
export const archivePlugin = (code) => http.post(`/admin/plugins/${code}/archive`);
export const restorePlugin = (code) => http.post(`/admin/plugins/${code}/restore`);
// v1.7.0-P0-07 soft uninstall (archive with task record; keep files/config/content)
export const getPluginUninstallImpact = (code) => http.get(`/admin/plugins/${encodeURIComponent(code)}/uninstall-impact`);
export const softUninstallPlugin = (code, payload) => http.post(`/admin/plugins/${encodeURIComponent(code)}/soft-uninstall`, payload);
export const listPluginUninstallTasks = (params) => http.get('/admin/plugins/uninstall-tasks', { params });
export const getPluginUninstallTask = (id) => http.get(`/admin/plugins/uninstall-tasks/${id}`);
export const retryPluginUninstallTask = (id) => http.post(`/admin/plugins/uninstall-tasks/${id}/retry`);
export const deletePluginUninstallTask = (id) => http.delete(`/admin/plugins/uninstall-tasks/${id}`);
export const bulkArchivePlugins = (payload) => http.post('/admin/plugins/bulk-archive', payload);
export const bulkRestorePlugins = (payload) => http.post('/admin/plugins/bulk-restore', payload);
export const updatePluginConfig = (code, payload) => http.put(`/admin/plugins/${code}/config`, payload);
export const pluginImpact = (code) => http.get(`/admin/plugins/${code}/impact`);
export const pluginHooks = (code) => http.get(`/admin/plugins/${code}/hooks`);
export const pluginHookExecutions = (code, params) => http.get(`/admin/plugins/${code}/hooks/executions`, { params });
export const pluginAuditLogs = (code, params) => http.get(`/admin/plugins/${code}/audit-logs`, { params });
export const pluginMigrations = (code) => http.get(`/admin/plugins/${code}/migrations`);
export const runPluginMigrations = (code) => http.post(`/admin/plugins/${code}/migrations/run`);
export const retryPluginMigration = (code, name) => http.post(`/admin/plugins/${code}/migrations/${encodeURIComponent(name)}/retry`);
export const adminCommunities = (params) => http.get('/admin/communities', { params });
export const createCommunity = (payload) => http.post('/admin/communities', payload);
export const adminCommunity = (id) => http.get(`/admin/communities/${id}`);
export const updateCommunity = (id, payload) => http.put(`/admin/communities/${id}`, payload);
export const enableCommunity = (id) => http.post(`/admin/communities/${id}/enable`);
export const disableCommunity = (id) => http.post(`/admin/communities/${id}/disable`);
export const reorderCommunities = (payload) => http.post('/admin/communities/reorder', payload);
export const adminCommunityPlugins = (id) => http.get(`/admin/communities/${id}/plugins`);
export const communityPluginImpact = (id, code) => http.get(`/admin/communities/${id}/plugins/${code}/impact`);
export const enableCommunityPlugin = (id, code) => http.post(`/admin/communities/${id}/plugins/${code}/enable`);
export const disableCommunityPlugin = (id, code) => http.post(`/admin/communities/${id}/plugins/${code}/disable`);
export const updateCommunityPluginConfig = (id, code, payload) => http.put(`/admin/communities/${id}/plugins/${code}/config`, payload);
export const reorderCommunityPlugins = (id, payload) => http.put(`/admin/communities/${id}/plugins/sort`, payload);
export const adminCommunityCategories = (id) => http.get(`/admin/communities/${id}/categories`);
export const createCommunityCategory = (id, payload) => http.post(`/admin/communities/${id}/categories`, payload);
export const updateCategory = (id, payload) => http.put(`/admin/categories/${id}`, payload);
export const enableCategory = (id) => http.post(`/admin/categories/${id}/enable`);
export const disableCategory = (id) => http.post(`/admin/categories/${id}/disable`);
export const reorderCategories = (payload) => http.post('/admin/categories/reorder', payload);
export const overview = (site) => http.get('/admin/overview', { params: { site } });
export const posts = (params) => http.get('/admin/posts', { params });
export const createPost = (payload) => http.post('/admin/posts', payload);
export const updatePost = (id, payload) => http.put(`/admin/posts/${id}`, payload);
export const deletePost = (id) => http.delete(`/admin/posts/${id}`);
export const batchTopics = (payload) => http.post('/admin/topics/batch', payload);
export const featureTopic = (id) => http.post(`/admin/topics/${id}/feature`);
export const pinTopic = (id) => http.post(`/admin/topics/${id}/pin`);
export const hideTopic = (id) => http.post(`/admin/topics/${id}/hide`);
export const restoreTopic = (id) => http.post(`/admin/topics/${id}/restore`);
export const lockTopicComments = (id) => http.post(`/admin/topics/${id}/lock-comments`);
export const unlockTopicComments = (id) => http.post(`/admin/topics/${id}/unlock-comments`);
export const comments = (site) => http.get('/admin/comments', { params: { site } });
export const updateComment = (id, payload) => http.put(`/admin/comments/${id}/status`, payload);
export const hideComment = (id) => http.post(`/admin/comments/${id}/hide`);
export const restoreComment = (id) => http.post(`/admin/comments/${id}/restore`);
export const deleteComment = (id) => http.delete(`/admin/comments/${id}`);
export const batchComments = (payload) => http.post('/admin/comments/batch', payload);
export const reports = (params) => http.get('/admin/reports', { params });
export const report = (id) => http.get(`/admin/reports/${id}`);
export const handleReport = (id, payload) => http.post(`/admin/reports/${id}/handle`, payload);
export const batchReports = (payload) => http.post('/admin/reports/batch-handle', payload);
export const batchHandleReports = batchReports;
export const moderators = (params) => http.get('/admin/moderators', { params });
export const createModerator = (payload) => http.post('/admin/moderators', payload);
export const updateModerator = (id, payload) => http.put(`/admin/moderators/${id}`, payload);
export const deleteModerator = (id) => http.delete(`/admin/moderators/${id}`);
export const updateModeratorStatus = (id, status) => http.put(`/admin/moderators/${id}`, { status });
export const users = () => http.get('/admin/users');
export const updateUserStatus = (id, payload) => http.put(`/admin/users/${id}/status`, payload);
export const roles = () => http.get('/admin/roles');
export const permissions = () => http.get('/admin/permissions');
export const tags = (params) => http.get('/admin/tags', { params });
export const tag = (id) => http.get(`/admin/tags/${id}`);
export const tagTopics = (id, params) => http.get(`/admin/tags/${id}/topics`, { params });
export const tagAliases = (id) => http.get(`/admin/tags/${id}/aliases`);
export const createTag = (payload) => http.post('/admin/tags', payload);
export const updateTag = (id, payload) => http.put(`/admin/tags/${id}`, payload);
export const createTagAlias = (id, payload) => http.post(`/admin/tags/${id}/aliases`, payload);
export const deleteTagAlias = (id, aliasId) => http.delete(`/admin/tags/${id}/aliases/${aliasId}`);
export const enableTag = (id) => http.post(`/admin/tags/${id}/enable`);
export const disableTag = (id) => http.post(`/admin/tags/${id}/disable`);
export const mergeTag = (id, payload) => http.post(`/admin/tags/${id}/merge`, payload);
export const recalculateTag = (id) => http.post(`/admin/tags/${id}/recalculate`);
export const recalculateAllTags = () => http.post('/admin/tags/recalculate-all');
export const logs = (site) => http.get('/admin/logs', { params: { site } });
export const auditLogs = (params) => http.get('/admin/audit-logs', { params });
export const settings = () => http.get('/admin/settings');
export const updateSettings = (payload) => http.put('/admin/settings', payload);
export const notices = (site) => http.get('/notifications', { params: { site } });
export const pushNotice = (payload) => http.post('/admin/notifications', payload);
