export {
  approvePluginApproval,
  approvePluginPackageUpload,
  blockTrustedPublisher,
  cancelPluginApproval,
  cancelPluginPackageUpload,
  cleanupPluginOperation,
  cleanupPluginPackageUploads,
  createPluginApproval,
  createPluginPackageTemplate,
  createPluginRemoteIndex,
  createTrustedPublisher,
  deletePluginPackageUpload,
  deletePluginRemoteIndex,
  deleteTrustedPublisher,
  disablePluginRemoteIndex,
  dryRunPluginConfigKeyRotation,
  dryRunPluginExport,
  dryRunPluginManifest,
  dryRunPluginPackage,
  dryRunPluginUpgrade,
  dryRunPluginUpgradeRollback,
  dryRunPluginVersionUpgradeDiff,
  enablePluginRemoteIndex,
  executePluginApproval,
  exportPluginPackage,
  fetchPluginRemoteIndex,
  getPluginConfigKeyStatus,
  getPluginOperation,
  getPluginPackageDetail,
  getPluginPackageUpload,
  getPluginRemoteIndexPlugin,
  getPluginVersionDetail,
  getTrustedPublisher,
  installPluginPackage,
  listPluginApprovals,
  listPluginCodeVersions,
  listPluginOperations,
  listPluginPackageUploads,
  listPluginPackages,
  listPluginRemoteIndexes,
  listPluginRemoteIndexPlugins,
  listPluginVersions,
  listTrustedPublishers,
  previewPluginPackageTemplate,
  promotePluginPackageUpload,
  recoverPluginOperationDryRun,
  reencryptPluginConfigKeys,
  rejectPluginApproval,
  rejectPluginPackageUpload,
  rescanPluginPackageUpload,
  restoreTrustedPublisher,
  revokeTrustedPublisher,
  submitPluginPackageUploadApproval,
  updatePluginRemoteIndex,
  updateTrustedPublisher,
  uploadPluginPackageZip,
  validatePluginManifest,
} from './admin';

export const pluginAPIGroups = {
  lifecycle: ['plugins', 'pluginHealth', 'pluginReadiness', 'enablePlugin', 'disablePlugin', 'archivePlugin', 'restorePlugin'],
  packages: ['listPluginPackages', 'getPluginPackageDetail', 'dryRunPluginPackage', 'installPluginPackage'],
  uploads: ['uploadPluginPackageZip', 'listPluginPackageUploads', 'getPluginPackageUpload', 'promotePluginPackageUpload'],
  security: ['listTrustedPublishers', 'getPluginConfigKeyStatus', 'dryRunPluginConfigKeyRotation', 'reencryptPluginConfigKeys'],
  approvals: ['createPluginApproval', 'listPluginApprovals', 'executePluginApproval'],
  operations: ['listPluginOperations', 'getPluginOperation', 'recoverPluginOperationDryRun', 'cleanupPluginOperation'],
  remoteIndexes: ['listPluginRemoteIndexes', 'fetchPluginRemoteIndex', 'listPluginRemoteIndexPlugins'],
  versions: ['listPluginVersions', 'dryRunPluginVersionUpgradeDiff'],
};
