export {
  approvePluginApproval,
  approvePluginPackageUpload,
  blockTrustedPublisher,
  cancelPluginApproval,
  cancelPluginPackageUpload,
  cleanupPluginOperation,
  cleanupPluginPackageUploads,
  cleanupPluginPackageRepository,
  createPluginApproval,
  createPluginPackageTemplate,
  createPluginRemoteIndex,
  createTrustedPublisher,
  deletePluginPackageUpload,
  deletePluginPackageRepository,
  deletePluginPackageStaging,
  deletePluginPackageCompatCheck,
  deletePluginPackageSignature,
  deletePluginEnablePrecheck,
  deletePluginRemoteIndex,
  deleteTrustedPublisher,
  disablePluginRemoteIndex,
  dryRunPluginConfigKeyRotation,
  dryRunPluginExport,
  dryRunPluginManifest,
  dryRunPluginPackage,
  dryRunPluginUpgrade,
  dryRunPluginUpgradeRollback,
  dryRunPluginVersionUpgradeDiff,
  downloadPluginPackageToStaging,
  enablePluginRemoteIndex,
  executePluginApproval,
  exportPluginPackage,
  exportPluginPackageTemplate,
  fetchPluginRemoteIndex,
  getPluginConfigKeyStatus,
  getPluginOperation,
  getPluginPackageDetail,
  getPluginPackageStaging,
  getPluginPackageCompatCheck,
  getPluginPackageUpload,
  getPluginRemoteIndexPlugin,
  getPluginVersionDetail,
  getTrustedPublisher,
  installPluginPackage,
  listPluginApprovals,
  listPluginCodeVersions,
  listPluginOperations,
  listPluginPackageUploads,
  listPluginPackageStaging,
  listPluginPackageCompatChecks,
  listPluginPackageSignatures,
  listPluginEnablePrechecks,
  listPluginEnableTasks,
  listPluginPackages,
  listPluginRemoteIndexes,
  listPluginRemoteIndexPlugins,
  listPluginVersions,
  listTrustedPublishers,
  previewPluginPackageTemplate,
  promotePluginPackageUpload,
  recoverPluginOperationDryRun,
  reencryptPluginConfigKeys,
  rejectPluginApproval,
  rejectPluginPackageUpload,
  rescanPluginPackageUpload,
  runPluginEnablePrecheck,
  enablePluginFromEnablePrecheck,
  getPluginEnableTask,
  retryPluginEnableTask,
  deletePluginEnableTask,
  deletePluginUninstallTask,
  restoreTrustedPublisher,
  getPluginEnablePrecheck,
  runPluginPackageCompatCheck,
  verifyPluginPackageSignature,
  revokeTrustedPublisher,
  submitPluginPackageUploadApproval,
  getPluginUninstallImpact,
  softUninstallPlugin,
  listPluginUninstallTasks,
  getPluginUninstallTask,
  retryPluginUninstallTask,
  pluginUpgradeImpact,
  upgradePluginFromPackage,
  listPluginUpgradeTasks,
  getPluginUpgradeTask,
  retryPluginUpgradeTask,
  deletePluginUpgradeTask,
  updatePluginRemoteIndex,
  updateTrustedPublisher,
  uploadPluginPackageZip,
  validatePluginManifest,
} from './admin';

export const pluginAPIGroups = {
  lifecycle: ['plugins', 'pluginHealth', 'pluginReadiness', 'enablePlugin', 'disablePlugin', 'archivePlugin', 'restorePlugin'],
  packages: ['listPluginPackages', 'getPluginPackageDetail', 'dryRunPluginPackage', 'installPluginPackage', 'deletePluginPackageRepository', 'cleanupPluginPackageRepository'],
  uploads: [
    'uploadPluginPackageZip',
    'listPluginPackageUploads',
    'getPluginPackageUpload',
    'deletePluginPackageUpload',
    'cleanupPluginPackageUploads',
    'promotePluginPackageUpload',
    'downloadPluginPackageToStaging',
    'listPluginPackageStaging',
    'runPluginPackageCompatCheck',
    'listPluginPackageCompatChecks',
    'verifyPluginPackageSignature',
    'listPluginPackageSignatures',
  ],
  enablePrechecks: ['runPluginEnablePrecheck', 'listPluginEnablePrechecks', 'getPluginEnablePrecheck', 'deletePluginEnablePrecheck'],
  enableTasks: ['enablePluginFromEnablePrecheck', 'listPluginEnableTasks', 'getPluginEnableTask', 'retryPluginEnableTask', 'deletePluginEnableTask'],
  uninstallTasks: ['getPluginUninstallImpact', 'softUninstallPlugin', 'listPluginUninstallTasks', 'getPluginUninstallTask', 'retryPluginUninstallTask', 'deletePluginUninstallTask'],
  upgradeTasks: ['pluginUpgradeImpact', 'upgradePluginFromPackage', 'listPluginUpgradeTasks', 'getPluginUpgradeTask', 'retryPluginUpgradeTask', 'deletePluginUpgradeTask'],
  security: ['listTrustedPublishers', 'getPluginConfigKeyStatus', 'dryRunPluginConfigKeyRotation', 'reencryptPluginConfigKeys'],
  approvals: ['createPluginApproval', 'listPluginApprovals', 'executePluginApproval'],
  operations: ['listPluginOperations', 'getPluginOperation', 'recoverPluginOperationDryRun', 'cleanupPluginOperation'],
  remoteIndexes: ['listPluginRemoteIndexes', 'fetchPluginRemoteIndex', 'listPluginRemoteIndexPlugins'],
  versions: ['listPluginVersions', 'dryRunPluginVersionUpgradeDiff'],
};
