import type { Board, Post, Site, TagStat } from './types';

export const fallbackSites: Site[] = [
  { key: 'portal', name: '总站', logo: 'DH', title: 'DevHub 开发者社区', sub: '多站点内容与社区 CMS', pub: '总站', description: '聚合 PHP、Go、Java 等技术站点的文章、问答、文档和开源项目。', color: '#2563eb', status: 'active', sort: 0 },
  { key: 'php', name: 'PHP', logo: 'PHP', title: 'PHP 开发者站', sub: '工程实践、框架生态、线上问题复盘', pub: 'PHP 子站', description: '面向 PHP 开发者的社区内容、文档、问答和项目推荐。', color: '#6478c8', status: 'active', sort: 1 },
  { key: 'go', name: 'Go', logo: 'Go', title: 'Go 开发者站', sub: '并发、服务端、云原生实践', pub: 'Go 子站', description: '聚焦 Go 服务端开发、性能优化、工程治理和云原生。', color: '#0891b2', status: 'active', sort: 2 },
  { key: 'java', name: 'Java', logo: 'JV', title: 'Java 开发者站', sub: '后端架构、中间件、企业工程实践', pub: 'Java 子站', description: '覆盖 Java 后端、Spring 生态、架构设计和线上治理。', color: '#ea580c', status: 'active', sort: 3 },
  { key: 'ai', name: 'AI', logo: 'AI', title: 'AI 开发者站', sub: 'Agent、RAG、Prompt 与工作流实践', pub: 'AI 子站', description: '聚合 AI Agent、RAG、Prompt 工程和自动化工作流内容。', color: '#7c3aed', status: 'active', sort: 4 },
  { key: 'frontend', name: '前端', logo: 'FE', title: '前端开发者站', sub: 'Vue、React、TypeScript、性能与工程化', pub: '前端子站', description: '面向现代前端开发者的工程实践、框架生态和性能优化内容。', color: '#16a34a', status: 'active', sort: 5 },
];

export const fallbackBoards: Board[] = [
  { key: 'community', name: '社区', site: 'portal', sort: 1, visible: true },
  { key: 'qa', name: '问答中心', site: 'portal', sort: 2, visible: true },
  { key: 'opensource', name: '开源项目', site: 'portal', sort: 3, visible: true },
  { key: 'ai', name: 'AI 作品', site: 'portal', sort: 4, visible: true },
  { key: 'jobs', name: '招聘内推', site: 'portal', sort: 5, visible: true },
  { key: 'wiki', name: 'Wiki', site: 'portal', sort: 6, visible: true },
  { key: 'docs', name: '文档', site: 'portal', sort: 7, visible: true },
];

export const fallbackPosts: Post[] = [
  {
    id: 1,
    site: 'php',
    board: 'community',
    title: '如何把多站点 CMS 的站点隔离做扎实',
    summary: '从 site_key、后台上下文、RBAC、审计日志四个角度梳理多站点 CMS 的基础模型。',
    content: '多站点 CMS 的关键不是把 URL 做出来，而是让数据模型、权限模型和审计模型都理解当前站点。site_admin 只能管理自己负责的站点，super_admin 才能跨站点操作。',
    author: 'DevHub Team',
    status: 'publish',
    pinned: true,
    recommended: true,
    content_type: 'article',
    favorite_count: 18,
    hot_score: 1124,
    last_active_at: '2026-05-08 13:30:00',
    views: 980,
    likes: 64,
    comments: 12,
    tags: ['CMS', 'RBAC', '多站点'],
    created_at: '2026-05-08 10:00:00',
    updated_at: '2026-05-08 10:00:00',
  },
  {
    id: 2,
    site: 'go',
    board: 'docs',
    title: 'Go + Gin 后端如何承载统一内容接口',
    summary: '围绕 store、service、transport 三层拆分，保证前台、后台和多站点复用同一套能力。',
    content: '当前后端已经把 domain、store、service、httpapi 分层。前台 Astro 只消费公开 API，后台 Vue Admin 消费后台 API，二者共享统一数据模型。',
    author: 'liuwei',
    status: 'publish',
    pinned: false,
    recommended: true,
    content_type: 'doc',
    favorite_count: 15,
    hot_score: 1040,
    last_active_at: '2026-05-08 14:10:00',
    views: 760,
    likes: 48,
    comments: 8,
    tags: ['Go', 'Gin', 'API'],
    created_at: '2026-05-08 11:00:00',
    updated_at: '2026-05-08 11:00:00',
  },
  {
    id: 3,
    site: 'java',
    board: 'qa',
    title: '内容站前台为什么不适合纯 SPA',
    summary: 'CMS 和社区的核心页面需要可索引 HTML，交互能力应该用局部组件增强。',
    content: '纯 SPA 对内容收录不稳定。Astro 可以让帖子详情、标签页和子站首页在构建时输出 HTML，再用 Vue Islands 承载登录、评论、点赞等交互。',
    author: 'CMS Notes',
    status: 'publish',
    pinned: false,
    recommended: false,
    solved: false,
    content_type: 'question',
    favorite_count: 9,
    hot_score: 860,
    last_active_at: '2026-05-08 15:00:00',
    views: 620,
    likes: 39,
    comments: 5,
    tags: ['SEO', 'Astro', 'Vue'],
    created_at: '2026-05-08 12:00:00',
    updated_at: '2026-05-08 12:00:00',
  },
  {
    id: 4,
    site: 'ai',
    board: 'ai',
    title: '如何设计一个可维护的 AI Agent 工作流',
    summary: '从工具调用、上下文压缩、任务状态和人工确认四个角度拆解 Agent 工程化。',
    content: 'AI Agent 的重点不是把模型接进来，而是把任务边界、工具权限、状态恢复和人工确认做清楚。DevHub 会把 AI 作品和工程笔记作为独立子站内容沉淀。',
    author: 'Agent Notes',
    status: 'publish',
    pinned: false,
    recommended: true,
    content_type: 'ai_work',
    favorite_count: 22,
    hot_score: 1180,
    last_active_at: '2026-05-08 16:10:00',
    views: 890,
    likes: 72,
    comments: 14,
    tags: ['AI Agent', 'RAG', '工作流'],
    created_at: '2026-05-08 16:00:00',
    updated_at: '2026-05-08 16:00:00',
  },
  {
    id: 5,
    site: 'frontend',
    board: 'opensource',
    title: '前端内容站如何组织组件和性能预算',
    summary: '用 Astro 输出 HTML，用 Vue Islands 承接局部交互，让内容站兼顾 SEO 和体验。',
    content: '内容型前台不适合纯 SPA。Astro 静态 HTML 能保证内容可索引，Vue Islands 负责登录、评论、点赞、发布入口等交互。',
    author: 'Frontend Lab',
    status: 'publish',
    pinned: false,
    recommended: true,
    content_type: 'project',
    favorite_count: 13,
    hot_score: 930,
    last_active_at: '2026-05-08 17:20:00',
    views: 710,
    likes: 46,
    comments: 9,
    tags: ['Vue', 'Astro', '性能优化'],
    created_at: '2026-05-08 17:00:00',
    updated_at: '2026-05-08 17:00:00',
  },
  {
    id: 6,
    site: 'php',
    board: 'jobs',
    title: 'PHP 团队招聘内推应该写清楚哪些信息',
    summary: '岗位职责、技术栈、远程政策、面试流程和薪资范围是社区招聘内容的基础字段。',
    content: '招聘内推也属于技术社区的重要内容类型。DevHub 会把招聘内容纳入统一 Topic 模型，同时保留站点隔离和标签能力。',
    author: 'Hiring Desk',
    status: 'publish',
    pinned: false,
    recommended: false,
    content_type: 'job',
    favorite_count: 6,
    hot_score: 540,
    last_active_at: '2026-05-08 18:20:00',
    views: 420,
    likes: 18,
    comments: 6,
    tags: ['招聘内推', 'PHP', '远程'],
    created_at: '2026-05-08 18:00:00',
    updated_at: '2026-05-08 18:00:00',
  },
];

export const fallbackTags: TagStat[] = [
  { name: 'CMS', count: 8 },
  { name: 'SEO', count: 6 },
  { name: 'Astro', count: 5 },
  { name: 'Vue', count: 5 },
  { name: 'RBAC', count: 4 },
  { name: 'Go', count: 4 },
  { name: 'AI Agent', count: 4 },
  { name: 'TypeScript', count: 3 },
];
